name: GitHub Action Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 5 * * 1-5'
jobs:
  test:
    name: Run end-to-end tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env :
      SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 15

    
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson (steps)}}
          channel: '#career-preps'
        if: always()
        # uses: slackapi/slack-github-action@v1.23.0
        # uses: pullreminders/slack-action@main
        # env:
        #   SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
        # with:
        #   args: '{\"channel\":\"C04QKFBN45C\",\"text\":\"An alert was generated for plawyright repo"}'

        

          # SLACK_CHANNEL: C04QKFBN45C
          # SLACK_TEXT: "An alert was generated for this repo: playwright"
